config/routes.rb
Games::Application.routes.draw do
  root to: 'games#index'

  resources :games

  resources :secret_numbers, only:[:new, :index]

  resources :app_names

end

app/models/app_name.rb
class AppName < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/app_names_controller.rb
class AppNamesController < ApplicationController
  before_action :set_app_name, only: [:show, :edit, :update, :destroy]

  # GET /app_names
  # GET /app_names.json
  def index
    @app_names = AppName.all
  end

  # GET /app_names/1
  # GET /app_names/1.json
  def show
  end

  # GET /app_names/new
  def new
    @app_name = AppName.new
  end

  # GET /app_names/1/edit
  def edit
  end

  # POST /app_names
  # POST /app_names.json
  def create
    @app_name = AppName.new(app_name_params)

    respond_to do |format|
      if @app_name.save
        format.html { redirect_to @app_name, notice: 'App name was successfully created.' }
        format.json { render action: 'show', status: :created, location: @app_name }
      else
        format.html { render action: 'new' }
        format.json { render json: @app_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_names/1
  # PATCH/PUT /app_names/1.json
  def update
    respond_to do |format|
      if @app_name.update(app_name_params)
        format.html { redirect_to @app_name, notice: 'App name was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_names/1
  # DELETE /app_names/1.json
  def destroy
    @app_name.destroy
    respond_to do |format|
      format.html { redirect_to app_names_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_name
      @app_name = AppName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_name_params
      params.require(:app_name).permit(:title, :players, :directions)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :players, :directions)
    end
end

app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController

	def new

	end

	def show
		@secret_number = rand(1..5)

		@chosen_number = params[:id].to_i
	end
end

app/helpers/app_names_helper.rb
module AppNamesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

app/views/app_names/_form.html.erb
<%= form_for(@app_name) do |f| %>
  <% if @app_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_name.errors.count, "error") %> prohibited this app_name from being saved:</h2>

      <ul>
      <% @app_name.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :players %><br>
    <%= f.number_field :players %>
  </div>
  <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_names/edit.html.erb
<h1>Editing app_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_name %> |
<%= link_to 'Back', app_names_path %>

app/views/app_names/index.html.erb
<h1>Listing app_names</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Players</th>
      <th>Directions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @app_names.each do |app_name| %>
      <tr>
        <td><%= app_name.title %></td>
        <td><%= app_name.players %></td>
        <td><%= app_name.directions %></td>
        <td><%= link_to 'Show', app_name %></td>
        <td><%= link_to 'Edit', edit_app_name_path(app_name) %></td>
        <td><%= link_to 'Destroy', app_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App name', new_app_name_path %>

app/views/app_names/new.html.erb
<h1>New app_name</h1>

<%= render 'form' %>

<%= link_to 'Back', app_names_path %>

app/views/app_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @app_name.title %>
</p>

<p>
  <strong>Players:</strong>
  <%= @app_name.players %>
</p>

<p>
  <strong>Directions:</strong>
  <%= @app_name.directions %>
</p>

<%= link_to 'Edit', edit_app_name_path(@app_name) %> |
<%= link_to 'Back', app_names_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :players %><br>
    <%= f.number_field :players %>
  </div>
  <div class="field">
    <%= f.label :directions %><br>
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Players</th>
      <th>Directions</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.players %></td>
        <td><%= game.directions %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<% if @secret_number == @chosen_number %>
	<h2> Congrats! You Won! </h2>
<% else %>
	<h2> Sorry, you lost</h2>
	<p>The secret number was <%= @secret_number %> </p>
<% end %>

<h3><%= link_to "Play Again" new_secret_numbers_path%> </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p>To play this game, all you have to do is guess a number. Click on a number below</p>

<% (1..5).each do |number| %>
	<%= link_to number, secret_number_path(number) %>
<% end %>